name: gallery_asset_picker
description: Medias picker which is inspired by modern app.
version: 0.0.1
homepage: https://github.com/haonguyenuet/gallery_asset_picker

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+2
  collection: ^1.16.0
  meta: ^1.7.0
  path: ^1.8.1
  photo_manager: ^3.0.0-dev.4
  uuid: ^4.2.1
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
